import { KeyType } from "../Types/type";

export const Keys: KeyType[] = [
  { content: "Q", state: "", isFunctionKey: false },
  { content: "W", state: "", isFunctionKey: false },
  { content: "E", state: "", isFunctionKey: false },
  { content: "R", state: "", isFunctionKey: false },
  { content: "T", state: "", isFunctionKey: false },
  { content: "Y", state: "", isFunctionKey: false },
  { content: "U", state: "", isFunctionKey: false },
  { content: "I", state: "", isFunctionKey: false },
  { content: "O", state: "", isFunctionKey: false },
  { content: "P", state: "", isFunctionKey: false },
  { content: "A", state: "", isFunctionKey: false },
  { content: "S", state: "", isFunctionKey: false },
  { content: "D", state: "", isFunctionKey: false },
  { content: "F", state: "", isFunctionKey: false },
  { content: "G", state: "", isFunctionKey: false },
  { content: "H", state: "", isFunctionKey: false },
  { content: "J", state: "", isFunctionKey: false },
  { content: "K", state: "", isFunctionKey: false },
  { content: "L", state: "", isFunctionKey: false },
  { content: "Enter", state: "", isFunctionKey: true },
  { content: "Z", state: "", isFunctionKey: false },
  { content: "X", state: "", isFunctionKey: false },
  { content: "C", state: "", isFunctionKey: false },
  { content: "V", state: "", isFunctionKey: false },
  { content: "B", state: "", isFunctionKey: false },
  { content: "N", state: "", isFunctionKey: false },
  { content: "M", state: "", isFunctionKey: false },
  { content: "BackSpace", state: "", isFunctionKey: true },
];

export const NumOfKeysAndOffset: [number, number][] = [
  [10, 0],
  [9, 10],
  [9, 19],
];

export const KeyToIndex: { [key: string]: number } = {
  Q: 0,
  W: 1,
  E: 2,
  R: 3,
  T: 4,
  Y: 5,
  U: 6,
  I: 7,
  O: 8,
  P: 9,
  A: 10,
  S: 11,
  D: 12,
  F: 13,
  G: 14,
  H: 15,
  J: 16,
  K: 17,
  L: 18,
  Z: 20, // 跳過19 因為那是Enter
  X: 21,
  C: 22,
  V: 23,
  B: 24,
  N: 25,
  M: 26,
};

export const initAnswerArea: [number, string][][] = [
  [
    [-1, ""],
    [-1, ""],
    [-1, ""],
    [-1, ""],
    [-1, ""],
  ],
  [
    [-1, ""],
    [-1, ""],
    [-1, ""],
    [-1, ""],
    [-1, ""],
  ],
  [
    [-1, ""],
    [-1, ""],
    [-1, ""],
    [-1, ""],
    [-1, ""],
  ],
  [
    [-1, ""],
    [-1, ""],
    [-1, ""],
    [-1, ""],
    [-1, ""],
  ],
  [
    [-1, ""],
    [-1, ""],
    [-1, ""],
    [-1, ""],
    [-1, ""],
  ],
  [
    [-1, ""],
    [-1, ""],
    [-1, ""],
    [-1, ""],
    [-1, ""],
  ],
];
